### ISSUE TITLE
Unable to use pcgc_r2.py in combination with --extract

### ISSUE THREAD

**Issue by MKBakker** [omerwe/S-PCGC#2]
Dear Omer,

I'm trying to implement s-PCGC and running the example with 1000G data. I'm able to run all steps with the toy example. I'm also able to tun pcgc_sync.py.

I run into an error with pcgc_r2.py:

> [INFO]  reading annot file...
/hpc/hers_en/mbakker2/tools/S-PCGC/pcgc_utils.py:56: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  df_chr = pd.read_table(fname, delim_whitespace=True, index_col=index_col, header=header, usecols=usecols)
/hpc/hers_en/mbakker2/tools/S-PCGC//pcgc_r2.py:29: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  df_sync = pd.read_table(args.sync+'sync', index_col='Category')
/hpc/hers_en/mbakker2/tools/S-PCGC//pcgc_r2.py:42: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  df_extract = pd.read_table(args.extract, squeeze=True, header=None)
[INFO]  Extracting 60 SNPs
[INFO]  Computing r^2 products for 60 SNPs
/hpc/hers_en/mbakker2/tools/S-PCGC//pcgc_r2.py:63: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  df_fam = pd.read_table(args.bfile+'.fam', header=None)
[INFO]  Loading SNP file...
After filtering, 60 SNPs remain
Traceback (most recent call last):
  File "/hpc/hers_en/mbakker2/tools/S-PCGC//pcgc_r2.py", line 115, in <module>
    df_prod_r2 = compute_r2_prod(args)
  File "/hpc/hers_en/mbakker2/tools/S-PCGC//pcgc_r2.py", line 73, in compute_r2_prod
    df_annotations = df_annotations.iloc[geno_array.kept_snps]
  File "/hpc/hers_en/mbakker2/tools/miniconda2/envs/pcgc/lib/python2.7/site-packages/pandas/core/indexing.py", line 1500, in \_\_getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/hpc/hers_en/mbakker2/tools/miniconda2/envs/pcgc/lib/python2.7/site-packages/pandas/core/indexing.py", line 2221, in _getitem_axis
    return self._get_list_axis(key, axis=axis)
  File "/hpc/hers_en/mbakker2/tools/miniconda2/envs/pcgc/lib/python2.7/site-packages/pandas/core/indexing.py", line 2203, in _get_list_axis
    raise IndexError("positional indexers are out-of-bounds")
IndexError: positional indexers are out-of-bounds

I used:
```
chr=22
python $PCGC/pcgc_r2.py \
    --annot $baseline/baselineLD.${chr}. \
    --sync $baseline/baselineLD. \
    --bfile $refDir/1000G_EUR_Phase3_plink/1000G.EUR.QC.${chr} \
    --extract $PCGC/example/good_snps.txt \
    --out $baseline/baselineLD.goodSNPs.${chr}
```

When I leave out `--extract $PCGC/example/good_snps.txt` PCGC runs fine and I get the expected output. But for all SNPs and not the 'good SNPs'

I tried to subset `good_snps.txt` to only the chr22 SNPs, but the same error occurs.

I am using conda to create an environment to run PCGC. This is created using
`conda create -n pcgc python=2.7 numpy pandas scikit-learn scipy tqdm bitarray`
And `conda list -n pcgc` gives:

> \# packages in environment at /hpc/hers_en/mbakker2/tools/miniconda2/envs/pcgc:
> \#
> \# Name                    Version                   Build  Channel
> atomicwrites              1.3.0                      py_0    conda-forge
> attrs                     19.1.0                     py_0    conda-forge
> backports_abc             0.5                        py_1    conda-forge
> bitarray                  0.8.3            py27h14c3975_0  
> blas                      1.0                         mkl  
> bokeh                     1.0.4                 py27_1000    conda-forge
> ca-certificates           2019.3.9             hecc5488_0    conda-forge
> certifi                   2019.3.9                 py27_0    conda-forge
> cffi                      1.12.2           py27hf0e25f4_1    conda-forge
> click                     7.0                        py_0    conda-forge
> cloudpickle               0.8.0                      py_0    conda-forge
> cytoolz                   0.9.0.1         py27h14c3975_1001    conda-forge
> dask                      1.1.4                      py_0    conda-forge
> dask-core                 1.1.4                      py_0    conda-forge
> distributed               1.26.0                   py27_1    conda-forge
> freetype                  2.9.1             h94bbf69_1005    conda-forge
> funcsigs                  1.0.2                      py_3    conda-forge
> futures                   3.2.0                 py27_1000    conda-forge
> heapdict                  1.0.0                 py27_1000    conda-forge
> intel-openmp              2019.1                      144  
> jinja2                    2.10                       py_1    conda-forge
> jpeg                      9c                h14c3975_1001    conda-forge
> libedit                   3.1.20181209         hc058e9b_0  
> libffi                    3.2.1                hd88cf55_4  
> libgcc-ng                 8.2.0                hdf63c60_1  
> libgfortran-ng            7.3.0                hdf63c60_0  
> libpng                    1.6.36            h84994c4_1000    conda-forge
> libstdcxx-ng              8.2.0                hdf63c60_1  
> libtiff                   4.0.10            h648cc4a_1001    conda-forge
> locket                    0.2.0                      py_2    conda-forge
> markupsafe                1.1.1            py27h14c3975_0    conda-forge
> mkl                       2019.1                      144  
> mkl_fft                   1.0.10           py27ha843d7b_0  
> mkl_random                1.0.2            py27hd81dba3_0  
> more-itertools            4.3.0                 py27_1000    conda-forge
> msgpack-python            0.6.1            py27h6bb024c_0    conda-forge
> ncurses                   6.1                  he6710b0_1  
> numpy                     1.16.2           py27h7e9f1db_0  
> numpy-base                1.16.2           py27hde5b4d6_0  
> olefile                   0.46                       py_0    conda-forge
> openssl                   1.1.1b               h14c3975_1    conda-forge
> packaging                 19.0                       py_0    conda-forge
> pandas                    0.24.1           py27he6710b0_0  
> pandas-plink              1.2.30           py27h14c3975_0    conda-forge
> partd                     0.3.9                      py_0    conda-forge
> pathlib2                  2.3.3                 py27_1000    conda-forge
> pillow                    5.3.0           py27h00a061d_1000    conda-forge
> pip                       19.0.3                   py27_0  
> pluggy                    0.9.0                      py_0    conda-forge
> psutil                    5.6.1            py27h14c3975_0    conda-forge
> py                        1.8.0                      py_0    conda-forge
> pycparser                 2.19                     py27_1    conda-forge
> pyparsing                 2.3.1                      py_0    conda-forge
> pytest                    4.3.1                    py27_0    conda-forge
> pytest-runner             4.4                        py_0    conda-forge
> python                    2.7.15               h9bab390_6  
> python-dateutil           2.8.0                    py27_0  
> pytz                      2018.9                   py27_0  
> pyyaml                    5.1              py27h14c3975_0    conda-forge
> readline                  7.0                  h7b6447c_5  
> scandir                   1.10.0           py27h14c3975_0    conda-forge
> scikit-learn              0.20.3           py27hd81dba3_0  
> scipy                     1.2.1            py27h7c811a0_0  
> setuptools                40.8.0                   py27_0  
> singledispatch            3.4.0.3               py27_1000    conda-forge
> six                       1.12.0                   py27_0  
> sortedcontainers          2.1.0                      py_0    conda-forge
> sqlite                    3.27.2               h7b6447c_0  
> tblib                     1.3.2                      py_1    conda-forge
> tk                        8.6.8                hbc83047_0  
> toolz                     0.9.0                      py_1    conda-forge
> tornado                   5.1.1           py27h14c3975_1000    conda-forge
> tqdm                      4.31.1                     py_0  
> wheel                     0.33.1                   py27_0  
> xz                        5.2.4             h14c3975_1001    conda-forge
> yaml                      0.1.7             h14c3975_1001    conda-forge
> zict                      0.1.4                      py_0    conda-forge
> zlib                      1.2.11               h7b6447c_3  
>

**Comment by omerwe** [comment]
Thanks for the catch! This is indeed a bug and I (hopefully) fixed it. Can you please pull the latest version and see if the problem is resolved?

**Comment by MKBakker** [comment]
Yes, thanks! 
After a simple `git pull` I'm now able to run pcgc_r2.py with the `--extract` option.
